name: Hello World Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual triggering
    # Define inputs if needed
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"
